### ISSUE TITLE
Upgraded Mule to 3.9.4 , APM stopped working

### ISSUE THREAD

**Issue by abhishekksingh2019** [michaelhyatt/elastic-apm-mule3-agent#30] opened 2020-06-30 16:25 UTC
APM stopped sending data to ECS after we update runtime  from 3.9.0 to 3.9.4 with Adopt Open JDK

**Comment by michaelhyatt** [comment] 2020-07-08 05:29
duplicate of #31

**Closed as completed by michaelhyatt** 2020-07-08 05:29 UTC
